version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
       - ./data:/data/db
    ports: 
      - "27017:27017"
    api:
      container_name: api-container
      build: .
      restart: always
      image: clean-node-api
      comand: npm start
      volumes: 
       - ./build:/usr/src/clean-node-api/build
      ports: 
        - "3333:3333"
      links: 
        - mongo